### ISSUE TITLE
Could have used <blockquote>

### ISSUE THREAD

**Issue by alextanasieiquest** [alexVee90/presentation-website#2]
https://github.com/alexVee90/presentation-website/blob/9d9550244aacdd1818b6faf8de5b1e89de0ab5c5/about.html#L96

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote

**Comment by alexVee90** [comment]
what would I put in the cite attribute?

**Comment by alextanasieiquest** [comment]
As can bee seen in the above documentation: 

> A URL for the source of the quotation may be given using the cite attribute, while a text representation of the source can be given using the <cite> element.

As can be oserved, the attribute *may* be mentioned, but it's not mandatory.
