### ISSUE TITLE
[Imp] <article> preferabil in <main>

### ISSUE THREAD

**Issue by Vlad-Iliescu** [alexVee90/presentation-website#6]
https://github.com/alexVee90/presentation-website/blob/9d9550244aacdd1818b6faf8de5b1e89de0ab5c5/index.html#L52

Fiind singurul article, as fi preferat sa fie in main contentul paginii sau #3.

**Comment by alexVee90** [comment]
am pus separat articolul pentru ca atunci cand vom stiliza site-ul, showcase-ul as vrea sa dispara pe mobile view

**Comment by Vlad-Iliescu** [comment]
Ideea e sa facem ceva progresiv, we cross that bridge when we get there. Chestia asta nu e gresit sintactic ci doar semantic (desi putin).

**Comment by alexVee90** [comment]
makes sense.
