### ISSUE TITLE
[Bug] Missing link to open in new page

### ISSUE THREAD

**Issue by Vlad-Iliescu** [alexVee90/presentation-website#8]
Una din cerinte era pe pagina de `about` sa fie un link ce se deschide in new window/tab.
Mai multe detalii [aici](https://www.w3schools.com/tags/att_a_target.asp).

**Comment by alexVee90** [comment]
am folosit in products page.

**Comment by Vlad-Iliescu** [comment]
Am observat, insa cerinta era pe pagina de about :)
